name: Notify PR opened

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}-${{ github.ref_name }}'

jobs:
  notify:
    name: Notify
    uses: cupel-co/workflows/.github/workflows/notify-pull-request.yml@v0.7.0
    secrets:
      google-chat-webhook-url: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
